version: "2"
services:
  cangateway:
    build: ./cangateway
    networks:
      canaero:
        ipv4_address: 172.20.4.4

  blackbox:
    build: ./blackbox
    depends_on:
      - cangateway
    networks:
      canaero:
        ipv4_address: 172.20.4.2

#  mcdu:
#    build: ./mcdu
#    depends_on:
#      - cangateway
#    networks:
#      canaero:
#        ipv4_address: 172.20.4.8

networks:
  canaero:
    ipam:
      config:
        - subnet: 172.20.4.0/24
