version: "2"
services:
  cangateway:
    build: ./cangateway
    networks:
      canaero:
        ipv4_address: 172.20.4.4

  blackbox:
    build: ./blackbox
    networks:
      canaero:
        ipv4_address: 172.20.4.2

  cdls:
    build: ./cdls
    networks:
      canaero:
        ipv4_address: 172.20.4.16

  mcdu:
    build: ./mcdu
    ports:
      - "127.0.0.1:9923:23"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      canaero:
        ipv4_address: 172.20.4.8

  router:
    build: ./router
    ports:
      - "8823:23"
    networks:
      canaero:
        ipv4_address: 172.20.4.32

networks:
  canaero:
    ipam:
      config:
        - subnet: 172.20.4.0/24
