version: "2"
services:
  blackbox:
    build: ./blackbox
    depends_on:
      - cangateway
    networks:
#      internet:
      canaero:
        ipv4_address: 172.20.4.2

  cangateway:
    build: ./cangateway
    networks:
      canaero:
        ipv4_address: 172.20.4.4

#  mcdu:
#    build: ./mcdu
#    networks:
#      canaero:
#        ipv4_address: 172.20.4.8
#      troubleshooting:
#        ipv4_address: 172.20.2.8

networks:
#  internet:

  canaero:
    internal: false
    ipam:
      config:
        - subnet: 172.20.4.0/24

#  troubleshooting:
#    ipam:
#      config:
#        - subnet: 172.20.2.0/24
